# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        informational: false
    patch: on

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: 'diff, files'
  require_changes: false

# https://docs.codecov.com/docs/node
parsers:
  javascript:
    enable_partials: no
