# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- next

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- bash: npm install
  displayName: 'npm install'

- bash: npm run eslint
  displayName: 'ESLint'

- bash: npm run build
  displayName: 'Build'

- bash: npm test
  displayName: 'Test'
  env: { 'CI': 'true' }

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true
