# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- next

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run eslint
  displayName: 'ESLint'

- script: npm run build
  displayName: 'Build'

- script: npm test
  displayName: 'Test'

- script: npx codecov
  displayName: 'Upload coverage reports'
