name: CI-bun
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Biome
        run: bun run biome:ci
      - name: ESLint
        run: bun run eslint
      - name: Prettier
        run: bun run prettier:check
      - name: Typecheck
        run: bun run typecheck
      - name: Bundle
        run: |
          bun run build
          bun run build:types
      - name: Test
        run: bun t
        timeout-minutes: 4
      - uses: codecov/codecov-action@v3

  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build
        run: |
          bun install
          bun run build:website
      - name: Set up git user
        if: github.event_name == 'push'
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
      - name: Deploy gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          git rm -r .
          git checkout gh-pages -- old
          mv ../dist/* .
          git add .
          git commit -m "gh-pages deployment" || echo "Nothing to commit"
          git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
