name: CI
on:
  push:
    branches: [master, alpha, canary, cdsb]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
    - name: npm install
      run: npm i
    - name: ESLint
      run: npm run eslint
    - name: Typecheck
      run: npm run typecheck
    - name: Test
      run: npm t -- --coverage --colors

  storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
    - uses: actions/cache@v1
      with:
        path: node_modules/.cache
        key: build-${{ hashFiles('package.json') }}
    - name: Build
      run: |
        npm i
        npm run build-storybook
    - name: Set up git user
      if: github.event_name == 'push'
      run: |
        git config --global user.email 'action@github.com'
        git config --global user.name 'GitHub Action'
    - name: Deploy alpha
      if: github.ref == 'refs/heads/alpha'
      run: npx gh-pages@^2 --dist storybook-static --dest alpha
    - name: Deploy canary
      if: github.ref == 'refs/heads/canary'
      run: npx gh-pages@^2 --dist storybook-static --dest canary
    - name: Deploy cdsb
      if: github.ref == 'refs/heads/cdsb'
      run: |
        git checkout --orphan gh-pages-canary
        git rm --cached $(git ls-files)
        git add -f storybook-static
        git mv storybook-static/* .
        git commit -m "storybook deployment"
        git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
