name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [18, 19]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true
      - name: Set up git user
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
      - name: merge react 19 branch
        if: matrix.react == 19
        run: |
          git fetch origin react19
          git merge origin/react19 -X theirs --allow-unrelated-histories
          git fetch origin main
          git diff origin/main
      - name: npm install
        run: npm i
      - name: Biome
        run: node --run biome:ci
      - name: ESLint
        run: node --run eslint
      - name: Prettier
        run: node --run prettier:check
      - name: Typecheck
        run: node --run typecheck
      - name: Bundle
        run: |
          node --run build
          node --run build:types
      - name: Build website
        run: node --run build:website
      - name: Test
        run: npm --run test
        timeout-minutes: 4
      - name: Upload coverage
        if: matrix.react == 18
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Deploy gh-pages
        if: matrix.react == 18 && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          git rm -r .
          git checkout gh-pages -- old
          mv ../dist/* .
          git add .
          git commit -m "gh-pages deployment" || echo "Nothing to commit"
          git push -f https://adazzle:${{secrets.GITHUB_TOKEN}}@github.com/adazzle/react-data-grid.git
