name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - name: npm install
        run: npm i
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier:check
      - name: Typecheck
        run: npm run typecheck
      - name: Bundle
        run: |
          npm run build
          npm run build:types
      - name: Test
        run: npm t -- --coverage --colors
      - uses: codecov/codecov-action@v3
