name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: npm install
      run: npm i
    - name: ESLint
      run: npm run eslint
    - name: Typecheck
      run: npm run typecheck
    - name: Build storybook
      run: npm run build-storybook
    - name: Test
      run: npm t -- --coverage
